---
# 程序设置
common:
  saveLog: false # 是否记录日志到文件[True/False]
  workersPerProject: 1 # 多线程，同时翻译的文件数量（单文件只能单线程）
  language: "ja2zh-cn" # 源语言2(to)目标语言。[zh-cn/zh-tw/en/ja/ko/ru/fr]
  linebreakSymbol: "\r\n" # 这个项目在json中使用的换行符，找问题和自动修复时用到，不影响翻译。
  skipRetry: false # 开启则解析结果出错时跳过循环重试，直接用"Fail Translation"占位。[True/False]
  retranslFail: false # 重启时重翻所有"Fail Translation"的句子。[True/False]
  retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
  gpt.numPerRequestTranslate: 10 # 单次翻译句子数量，推荐值 < 15
  gpt.streamOutputMode: true # 流式输出效果，多线程下无效。[True/False]
  # NewBing/GPT4
  gpt.enableProofRead: false # (NewBing/GPT4)是否开启译后校润。[True/False]
  gpt.numPerRequestProofRead: 7 # (NewBing/GPT4)单次校润句子数量，不建议修改
  gpt.recordConfidence: false # (NewBing/GPT4)记录确信度、存疑句，GPT4 API关掉可节约token。[True/False]
  # GPT3.5/GPT4
  gpt.restoreContextMode: true # (GPT3.5/4)重启时恢复上一轮的译文前文。[True/False]
  gpt.fullContextMode: false # (GPT3.5/4)(将废弃)保留更多前文。默认关闭，节约token消耗。[True/False]
# 插件设置
plugin:
  filePlugin: file_galtransl_json # 指定文件读取插件，默认使用file_galtransl_json
  textPlugins: # 文本处理插件列表，按顺序执行
    - text_common_normalfix # 默认插件，修复常规通用问题
    - (project_dir)text_common_example # 示例，(project_dir)代表插件在项目的plugins目录里
# 代理设置
proxy:
  enableProxy: false # 是否启用代理。[True/False]
  proxies:
    - address: http://127.0.0.1:7890
# 字典设置
dictionary:
  defaultDictFolder: Dict # 通用字典文件夹，相对于程序目录，也可填入绝对路径
  usePreDictInName: false # 将译前字典用在name字段，可用于改名[True/False]
  usePostDictInName: false # 将译后字典用在name字段，可用于汉化name[True/False]
  # 所有字典、字典内词条将按顺序从上到下替换
  # 译前字典
  preDict:
    - 01H字典_矫正_译前.txt # 用于口齿不清的矫正
    - 00通用字典_译前.txt
    - (project_dir)项目字典_译前.txt # (project_dir)代表字典在项目文件夹
  # GPT 字典
  gpt.dict:
    - GPT字典.txt
    - (project_dir)项目GPT字典.txt
  # 译后字典
  postDict:
    - 00通用字典_符号_译后.txt # 符号矫正
    - 00通用字典_译后.txt
    - (project_dir)项目字典_译后.txt
# 翻译后端相关设置
backendSpecific:
  GPT35: # GPT3.5 API/claude-3-sonnet第三方中转
    tokens:
      - token: sk-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        endpoint: https://api.openai.com # OpenAI API请求的域名，使用转发或第三方API时修改
      - token: sk-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        endpoint: ""
    defaultEndpoint: https://api.openai.com # 默认 API 端点，一般不修改
    rewriteModelName: "" # 强制使用指定的模型型号，可用于claude-3-sonnet第三方中转
  GPT4: # GPT4 API/claude-3-opus第三方中转
    tokens:
      - token: sk-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        endpoint: https://api.openai.com # 使用转发或第三方API时修改
    defaultEndpoint: https://api.openai.com # 一般不修改
    rewriteModelName: "" # 强制使用指定的模型型号，可用于claude-3-opus第三方中转
  bingGPT4: # NewBing API
    cookiePath:
      - newbing_cookies/cookie1.json # 你的 cookies 文件，相对于项目目录
      - newbing_cookies/cookie2.json # 你的 cookies 文件2，会自动切换
  Sakura: # Sakura API
    endpoint: http://127.0.0.1:8080
# 自动问题分析配置
problemAnalyze: 
  problemList: # 要发现的问题清单
    - 词频过高
    - 标点错漏
    - 残留日文
    - 丢失换行
    - 多加换行
    - 比日文长
    - 字典使用
  arinashiDict: # 格式为 aaa:<空格>bbb
    aaa: bbb
    ccc: ddd
