---
# 通用（杂项）设置
common:
  loggingLevel: info # 日志等级，可选 [debug/info/warning/error]
  workersPerProject: 1 # workers 数量，为 1 时等于单线程
  # 通用设置
  sourceLanguage: ja # 源语言。[zh-cn/zh-tw/en/ja/ko/ru/fr]
  targetLanguage: zh-cn # 目标语言。[zh-cn/zh-tw/en/ja/ko/ru/fr]
  retranslFail: false # 启动后重翻NewBing拒绝翻译的句子。[True/False]
  retranslKey: "" # 主动重翻在Problem或pre_zh中包含设置的关键字的句子，例如"残留日文"
  gpt.numPerRequestTranslate: 9 # 单次翻译句子数量，不建议太大
  gpt.streamOutputMode: true # 流式输出/打字机效果，开启方便观察过程，关闭方便观察结果。[True/False]
  # NewBing/GPT4
  gpt.enableProofRead: false # (NewBing/GPT4)是否开启译后校润。[True/False]
  gpt.numPerRequestProofRead: 7 # (NewBing/GPT4)单次校润句子数量，不建议修改
  gpt.recordConfidence: false # (NewBing/GPT4)记录确信度、存疑句，GPT4官方API关掉可节约token。[True/False]
  gpt.forceNewBingHs: false # (NewBing)强制NewBing翻译hs，导致速度变得很慢且可能更容易被ban号。[True/False]
  # GPT3.5/GPT4
  gpt.translStyle: auto # (GPT3.5/4 官方API)GPT参数预设，precise更精确normal更随机，auto自动切换。[auto/precise/normal]
  gpt.degradeBackend: false # (GPT3.5/4 官方API)是否将 GPT4 的key用于 GPT3.5 的请求。[True/False]
  gpt.restoreContextMode: true # (GPT3.5/4 官方API)重启时恢复上一轮的译文前文。[True/False]
  gpt.fullContextMode: false # (GPT3.5/4 官方API)保留更多前文。开启提升效果，关闭节约数倍token消耗。[True/False]
  gpt.lineBreaksImprovementMode: false # (GPT3.5)换行符改善模式，部分减少丢换行符情况，但可能导致循环重试。[True/False]
# 代理设置
proxy:
  enableProxy: false # 是否启用代理。[True/False]
  proxies:
    - address: http://127.0.0.1:7890
      # username: foo
      # password: bar
# 字典
dictionary:
  defaultDictFolder: Dict # 通用字典文件夹，相对于程序目录
  # 预处理字典
  preDict:
    - 00通用字典_译前.txt
    - 01H字典_矫正_译前.txt # 用于口齿不清的矫正
    - (project_dir)项目字典_译前.txt # (project_dir)代表字典在项目文件夹
  # GPT 字典
  gpt.dict:
    - GPT字典.txt
    - (project_dir)项目GPT字典.txt
  # 后处理字典
  postDict:
    - 00通用字典_符号_译后.txt # 符号矫正
    - 00通用字典_译后.txt
    - (project_dir)项目字典_译后.txt
# 与翻译后端所特定的设置
backendSpecific:
  GPT35: # GPT3.5 官方 API
    tokens: # 令牌列表
      # 你的api key
      - token: sk-xxxxxxxx
        # OPENAI API请求的域名，使用转发或第三方API时修改
        endpoint: https://api.openai.com
      - token: sk-yyyyyyyy
        endpoint: ""
    defaultEndpoint: https://api.openai.com # 默认 API 端点，一般不修改
  GPT4: # GPT4 官方 API
    tokens:
      - token: sk-xxxxxxxx
        endpoint: ""
      - token: sk-yyyyyyyy
        endpoint: ""
    defaultEndpoint: https://api.openai.com
  ChatGPT: # ChatGPT / GPT3.5(4) 非官方 API，模拟网页操作模式
    access_tokens: # 访问https://chat.openai.com/api/auth/session，提取accessToken
      - access_token: xxx
    accounts: # 暂不支持
      - username: foo
        password: bar
  bingGPT4:
    cookiePath:
      - newbing_cookies/cookie1.json # 你的 cookies 文件，相对于项目目录
      - newbing_cookies/cookie2.json # 你的 cookies 文件2
# 问题分析机制配置
problemAnalyze:
  GPT35: # GPT35 / ChatGPT
    - 词频过高
    - 标点错漏
    - 残留日文
    - 丢失换行
    - 多加换行
    - 比日文长
  GPT4: # GPT4 / ChatGPT
    - 词频过高
    - 标点错漏
    - 残留日文
    - 丢失换行
    - 多加换行
  bingGPT4: # NewBing
    - 词频过高
    - 标点错漏
    - 残留日文
    - 丢失换行
    - 多加换行
  arinashiDict: # 格式为 aaa:<空格>bbb
    aaa: bbb
    ccc: ddd
